<a href="https://colab.research.google.com/github/RNAB100/Learning_Pytorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device = device) #gpu
  y = torch.ones(5) #cpu
  y = y.to(device) #cpu to gpu
  z = x + y
  z = z.to("cpu")


**Autograd**

In [ ]:
import torch

a = torch.tensor([5.], requires_grad = True)
b = torch.tensor([6.], requires_grad = True)

y = a**3 - b**2
print(a)
print(b)
y.backward()
a.grad  #dy/da
b.grad  #dy/db
print(a.grad)
print(b.grad)

W = torch.rand(10, 1, requires_grad = True) #gradient func for tracking previous values
b = torch.rand(1, requires_grad = True)
x = torch.rand(1, 10)
output = torch.matmul(x, W) + b #linear reg

J = 1 - output
J.backward()
W.grad
b.grad

#gradient Descent
with torch.no_grad() : #this line is to find only updated values without gradient function
  W = W - 0.001 * W.grad.data
  b = b - 0.001 * b.grad.data
print(W)
print(b)

tensor([5.], requires_grad=True)
tensor([6.], requires_grad=True)
tensor([75.])
tensor([-12.])
tensor([[0.4285],
        [0.4241],
        [0.4801],
        [0.1894],
        [0.0281],
        [0.4519],
        [0.5558],
        [0.3608],
        [0.1847],
        [0.2995]])
tensor([0.6776])


**Backpropagation**

In [ ]:
import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad = True)
#forward pass
y_hat = w * x
loss = (y_hat - y)**2

#backward pass
loss.backward()
print(w.grad)


tensor(-2.)


**Model Implementation with Pytorch**

In [ ]:
import torch
import torch.nn as nn

x = torch.tensor([1, 2, 3, 4], dtype = torch.float32)
y = torch.tensor([2, 4, 6, 8], dtype = torch.float32)

w = torch.tensor(0.0, dtype = torch.float32, requires_grad = True)

#forward propagation
def forward(x) :
  return w * x

#training
learning_rate = 0.01
no_of_iterations = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD([w], lr = learning_rate)

for epoch in range(no_of_iterations):
  y_hat = forward(x)

  l = loss(y, y_hat)
  #gradient tracks how the loss is genarated
  l.backward()

  optimizer.step()

  #zero_grad
  optimizer.zero_grad()

  if epoch % 10 == 0:
    print(f'Epoch = {epoch + 1} W = {w:.8f} loss = {l:.8f}')


Epoch = 1 W = 0.29999998 loss = 30.00000000
Epoch = 11 W = 1.66531360 loss = 1.16278565
Epoch = 21 W = 1.93410885 loss = 0.04506890
Epoch = 31 W = 1.98702765 loss = 0.00174685
Epoch = 41 W = 1.99744618 loss = 0.00006770
Epoch = 51 W = 1.99949718 loss = 0.00000262
Epoch = 61 W = 1.99990106 loss = 0.00000010
Epoch = 71 W = 1.99998045 loss = 0.00000000
Epoch = 81 W = 1.99999630 loss = 0.00000000
Epoch = 91 W = 1.99999928 loss = 0.00000000
